---
title: "Why I Write"
author: "Bryan Whiting"
description: |
  Some additional details about the blog
date: 2017-06-23
showthedate: false
---

I want to share. I believe that writing is a process where scrambled thoughts can be converted into shareable information.

In math, processes are called functions. In writing, my thoughts are the inputs, writing is the function, and this post is my output. In statistics, the truth is unattainable, only estimable. Writing is the function that uses my thoughts to estimate truth. And bias is the distance from the truth. In reading my writing, there are two biases at play for you: my writing's distance from the truth and your distance from understanding my writing. I hope by writing often I can reduce both sources of bias. Better writing means better sharing, and sharing truth helps us both.

My hope is that those who read this blog will take away from it a portion of what I've gained from others. It's likely that this blog is more valueable for me than it is for you, but I hope that what I've learned can help. If it does, please share.

# About me

I received a BS and MS in Statistics from Brigham Young University. During that time, I first learned to code in R and SAS. Since then, I've learned Stata, Excel Visual Basic for Applications (VBA), Python, [vi], and [RShiny]. I love to build innovative products, work with data, learn something new, and share what I learn.

In my spare time, I enjoy guitar, drawing, and learning golf. If I had snow nearby, I would ski it.

[^1]: And by milk I mean webscrape. (I needed an "m" for alliteration.)
[Bates White]:http://www.bateswhite.com/ 
[vi]:https://en.wikipedia.org/wiki/Vi
[RShiny]:http://shiny.rstudio.com/

