---
title: "workouts"
author: "Bryan Whiting"
date: "11/16/2021"
draft: true
output:
  distill::distill_article:
    code_folding: true
    toc: true
editor_options: 
  markdown: 
    wrap: 72
---

Goals: 

* Set a new record every month. Identify where that's easy to
do. 
* Track progress: am I hitting my goals? (run mileage) 
* Motivate myself by hitting consistency. 
* Give myself knowledge to know what goals I can set and how to achieve them (average watts, pace)


<!-- TODO: -->

<!-- 


-->


```{r setup, include=FALSE}
here::i_am('workouts.Rmd')
knitr::opts_chunk$set(echo = T, message = F, warning=F)
xaringanExtra::use_panelset()


library(here)
library(directlabels)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(gt)
library(glue)
library(gridExtra)
# https://github.com/lgellis/pelotonR
# devtools::install_github("lgellis/pelotonR")
library(pelotonR)
# https://github.com/fawda123/rStrava
# install.packages('rStrava')
library(rStrava)
library(ggthemes)
theme_set(theme_pander())
source(here('R/peloton_strava.R'))
colors = palette_pander(8)
```

```{r authenticate}
authenticate(username = 'myem',
             password = 'sp')

my_strava_id <- 23456
app_name <- 'workout_dashboard' # chosen by user
app_client_id  <- '###' # an integer, assigned by Strava
app_secret <- '####' # an alphanumeric secret, assigned by Strava

# create the authentication token
stoken <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, app_scope="activity:read_all", cache=TRUE))

# TODO: open localhost 1410 port to the docker
# stoken <- httr::config(token = readRDS('~/data/.httr-oauth')[[1]])

```

```{r prep_data}
# Peloton data
df_rides_raw <- load_peloton_workouts()
df_rides <- df_rides_raw %>%
  filter(metrics_type == 'cycling') %>%
  filter(total_work/1000 > 30) %>% # not real workout
  select(
    date,
    duration,
    kj,
    rank,
    is_total_work_personal_record,
    avg_watts,
    pr_local,
    pr_global
  ) %>%
  mutate_dates()

# Strava
df_runs <- load_strava_data(stoken = stoken)

```

# Dashboard

```{r, calendar_plot, layout="l-body-outset", fig.width=10, fig.height=4}
# Plot days active
all_days <- seq(floor_date(Sys.Date() - 364, unit='week'), 
                floor_date(Sys.Date() + 14, unit='week') - 1, 
                by="days")

df_days <- tibble(date = all_days) %>% 
  mutate_dates()

# Records:
df_ride_records <- df_rides %>%
  filter(pr_local | pr_global)
df_run_records <- df_runs %>% 
  filter(pr_local | pr_global)
  
df_runs <- df_runs %>%
  filter(type == 'Run') %>%
  mutate_dates()

# CALEDNAR PLOT: https://www.royfrancis.com/calendar-plot-with-ggplot2/
# TODO: find a way to outline left side only if it's calendar dates 1-7.
weekly_ride_tallies <- df_rides %>%
    mutate_dates() %>% 
    group_by(week) %>% 
  summarize(
    n = n(),
    max_kj = max(kj), 
    sum_kj = sum(kj)) %>%
  mutate(kj_str = glue("({floor(max_kj)}) {floor(sum_kj/100)}"))

weekly_run_tallies <- df_runs %>%
  group_by(week) %>%
  summarize(n = n(), 
            miles = floor(sum(distance_miles)),
            max = floor(max(distance_miles))) %>%
  mutate(miles_str = glue("{miles} ({max})"))


# runs and rides
df_both <- df_runs %>% select(date) %>%
  inner_join(df_rides %>% select(date), by = "date")  %>%
  mutate_dates()


# Gray color scales: https://www.canva.com/colors/color-meanings/off-white/
# border = "#C7C7C7"
border <- "#DEDEDE"
border <- "#F5F5F5"
border <- "white"
df_rides %>%
  ggplot(aes(x = week, y = wday)) + 
  geom_tile(data = filter(df_days, month %% 2 == 1), 
            aes(x = week, y = wday), 
            fill='#DEDEDE', alpha = .4, color=border) +
  geom_tile(data = filter(df_days, month %% 2 == 0), 
            aes(x = week, y = wday), 
            fill='#DEDEDE', alpha = .7, color=border) +
  # ride tile: blue
  geom_tile(fill = colors[1], color = border) + 
  # run tile: green
  geom_tile(data = df_runs, aes(x=week, y = wday), 
            fill = colors[2], color = border) + 
  # both tile: 
  # geom_tile(data = df_both, aes(x=week, y = wday), 
  #           fill = colors[3], color = border) + 
  # Run stats
  geom_text(data = weekly_run_tallies, 
            aes(x = week, y = 8, label=n), size=3) + 
  geom_text(data = weekly_run_tallies, 
            aes(x = week, y = 9, label=miles_str), 
            angle=90, size=3, hjust = 0) + 
  geom_point(data=filter(df_run_records, pr_local), 
             color = colors[3], 
             shape = 15, size = 1) +
  geom_point(
    data=filter(df_run_records, pr_global),
    color = colors[3],
    shape = "\u2726", size = 5) +
  # Ride stats
  geom_text(data = weekly_ride_tallies, 
            aes(x = week, y = 0, label=n), size=3) + 
  geom_text(data = weekly_ride_tallies, 
            aes(x = week, y = -1, label=kj_str), 
            angle=90,
            hjust = 1,
            size=3) + 
  # Ride records
  geom_point(data=df_ride_records,
             aes(x = week, y = wday),
             color = colors[3],
             shape = 15, size = 1)  +
  geom_point(
    data=filter(df_ride_records, pr_global),
    color = colors[3],
    shape = "\u2726", size = 5) +
  # label the days with calendar number:
  # geom_text(data=df_days, 
  #           aes(x = week, y = wday, label = mday), size = 2) + 
  # geom_text(aes(label = mday), size=2) +
  scale_y_continuous(
    labels = c("KJ (Best)", "# Rides", 
               "S", "M","T","W","T","F","S", 
               "# Runs", "Miles"), 
    breaks = -1:9, limits = c(-3.5, 11)) +
    # expand = c(0, 0))# +
  scale_x_date(
    date_labels = "%b", 
    date_breaks = '1 month', 
    position = "top",
    expand = c(0, 0)) + 
      # facet_grid(~month,scales="free",space="free")+
  labs(y = "", x = "", 
       title = 
         glue(
           "<span style='color:{colors[2]}'>**Runs**</span>
           and 
           <span style='color:{colors[1]}'>**Rides**</span>
           ")) +
  theme_bw(base_size=10)+
      theme(
        plot.title = ggtext::element_markdown(hjust = 0.5),
        legend.title=element_blank(),
        panel.grid=element_blank(),
        panel.border=element_blank(),
        axis.ticks=element_blank(),
        strip.background=element_blank(),
        legend.position="top",
        legend.justification="right",
        legend.direction="horizontal",
        legend.key.size=unit(0.3,"cm"),
        legend.spacing.x=unit(0.2,"cm")
      ) + 
  theme(
    axis.line.x = element_line(color = 'light gray'),
  )
```




# Biking

```{r peloton_plots, layout="l-body-outset", fig.width=15, fig.height=6}

p_kj_date <- df_rides %>% 
  ggplot(aes(x = date, y = kj, color = duration)) + 
  geom_point() +
  scale_color_pander() + 
  labs(title = 'KJ', x = '', y = '') + 
  guides(color='none') +
  geom_dl(aes(label = duration), 
          method = list('maxvar.points', hjust = 1.5, vjust = .5))

p_kj_date_line <- df_rides %>% 
  ggplot(aes(x = date, y = kj, color = duration)) + 
  geom_line() + 
  geom_point() +
  scale_color_pander() + 
  labs(title = 'KJ per Ride by Duration', x = '', y = '') + 
  guides(color='none') +
  geom_dl(aes(label = duration), 
          method = list('last.points', hjust = -.2))
  

p_kj_idx <- ggplot(df_rides, aes(x = rank, y = kj, color = duration)) +
  geom_point(data=filter(df_rides, is_total_work_personal_record),
  aes(x = rank, y = kj), shape="\u2605", size = 5) + 
  geom_point() +
  geom_line() + 
  theme(legend.position = 'none') + 
  scale_color_pander() + 
  geom_dl(aes(label = duration), 
          method = list('last.points', hjust = -.2)) + 
  labs(
    title = 'KJ per Ride by Index',
    y = "",
    x = ""
  ) 

# ggplot(df_rides, aes(x = date, y = pace, color = duration)) +
#   geom_point(data=filter(df_rides, is_total_work_personal_record),
#   aes(x = date, y = pace, color=duration), 
#     shape="\u2605", size = 5) + 
#   geom_point() +
#   geom_line() +
#   # geom_line(data=df_rides, aes(x = date, y = pace)) +
#   theme(legend.position = 'none') + 
#   scale_color_pander() + 
#   geom_dl(
#     aes(label = duration), method = list('last.points', hjust = -.2)
#   ) +
#   labs(
#     title = 'KJ per Min',
#     y = "",
#     x = ""
#   )

p_watts_idx <- ggplot(df_rides, aes(x = rank, y = avg_watts, color = duration)) +
  geom_line() + 
  geom_point() + 
  labs(title = 'Average Watts by Index', x='', y ='') +
  guides(color='none') + 
  scale_color_pander() + 
  geom_dl(aes(label = duration), 
          method = list('last.points', hjust = -.2)) 

# Avg Watts line chart
p_watts_date <- ggplot(df_rides, aes(x = date, y = avg_watts, color=duration)) +
  geom_point() + 
  labs(title = 'Average Watts', y = '', x = '') +
  scale_color_pander() + 
  guides(color='none') + 
  geom_dl(aes(label = duration), 
          method = list('maxvar.points', hjust = -.2)) 

p_watts_date_line <- ggplot(df_rides, aes(x = date, y = avg_watts, color = duration)) +
  geom_point(data=filter(df_rides, is_total_work_personal_record),
  aes(x = date, y = avg_watts, color=duration), shape="\u2605", size = 5) + 
  geom_point() +
  geom_line() +
  theme(legend.position = 'none') + 
  scale_color_pander() + 
  geom_dl(
    aes(label = duration), 
    method = list('last.points', hjust = -.2)) +
  labs(
    title = 'Average Watts by Duration',
    y = "",
    x = ""
  )

grid.arrange(
  p_kj_date, p_kj_idx, p_kj_date_line,
  p_watts_date, p_watts_idx, p_watts_date_line,
  nrow=2
)
```


```{r peloton_table}
# Table: Best ride, Last ride
best_rides <- df_rides %>%
  group_by(duration) %>%
  filter(kj == max(kj)) %>%
  select(duration, date_best = date, kj_best = kj, avg_watts_best = avg_watts)

last_rides <- df_rides %>%
  group_by(duration) %>%
  filter(date == max(date)) %>%
  select(duration, date_last = date, kj_last = kj, avg_watts_last = avg_watts)

n_rides <- df_rides %>%
  count(duration)

# dates of best rides
best_rides %>% 
  left_join(last_rides, by = 'duration') %>%
  left_join(n_rides, by = 'duration') %>%
  # mutate(date_diff_best = difftime(date_best, Sys.Date(), 'days')) %>%
  mutate(
    date_diff_best = as.character(Sys.Date() - date_best),
    date_diff_last = as.character(Sys.Date() - date_last),
    ) %>%
  ungroup() %>%
  arrange(duration) %>%
  select(duration, n, everything()) %>%
  gt() %>%
  fmt_date(c(date_best, date_last), date_style='day_m_year') %>%
  fmt_number(c(kj_best, kj_last), decimals = 0) %>%
  fmt_number(starts_with("avg"), decimals = 0) %>%
  cols_merge(
    columns = c(kj_best, avg_watts_best, date_best, date_diff_best),
    pattern = "{1} ({2}w)<br><span style='font-size:10px'>{3} (-{4}d)</span>"
  )  %>%
  cols_merge(
    columns = c(kj_last, avg_watts_last, date_last, date_diff_last),
    pattern = "{1} ({2}w)<br><span style='font-size:10px'>{3} (-{4}d)</span>"
  ) %>%
  cols_label(
    n = 'Total Rides',
    duration = "Length",
    kj_best = "Best Ride",
    kj_last = "Last Ride"
  ) %>%
  cols_align(columns = n, align='center')
  # cols_merge()

# Table of last 5 rides
df_rides %>%
  arrange(desc(date)) %>%
  head(10) %>%
  mutate(duration = ifelse(
    is_total_work_personal_record, 
    glue('{duration}*'),
    glue('{duration}')
  )) %>%
  select(date, duration, kj, avg_watts) %>%
  mutate(date = format(date, '%a, %b %d')) %>%
  gt() %>%
  fmt_number(c(kj, avg_watts), decimals = 0) %>%
  tab_header(
    title = 'Last 10 Rides'
  ) %>%
  cols_align(align = 'center', columns = 2:4) %>%
  cols_label(
    date = 'Date',
    duration = 'Duration',
    kj = "KJ",
    avg_watts = 'Avg Watts'
  )
```

# Runs

```{r load_strava}
total_run <- df_runs %>%
  group_by(duration) %>%
  summarize(
    n_runs = n(),
    total_miles = floor(sum(distance_miles)),
  )

best_run <- df_runs %>%
  filter(pace < 50) %>% 
  group_by(duration) %>%
  filter(pace == min(pace)) %>%
  select(duration, 
         date_best = date, 
         pace_best = pace_str, 
         minutes_best = minutes_str,
         distance_miles_best = distance_miles)
  
last_run <- df_runs %>%
  filter(pace < 50) %>% 
  group_by(duration) %>%
  filter(date == max(date)) %>%
  select(duration, 
         date_last = date, 
         pace_last = pace_str, 
         minutes_last = minutes_str,
         distance_miles_last = distance_miles)


run_pattern = "{1} ({3}m, {2})<br><span style='font-size:10px'>{4} (-{5}d)</span>"

total_run %>% 
  left_join(best_run, by = 'duration') %>%
  left_join(last_run, by = 'duration') %>%
  # mutate(date_diff_best = difftime(date_best, Sys.Date(), 'days')) %>%
  mutate(
    date_diff_best = as.character(Sys.Date() - date_best),
    date_diff_last = as.character(Sys.Date() - date_last),
    ) %>%
  ungroup() %>%
  gt() %>%
  fmt_date(c(date_best, date_last), date_style='day_m_year') %>%
  fmt_number(starts_with('distance'), decimals = 1) %>%
  cols_merge(
    columns = c(minutes_best, pace_best, distance_miles_best, date_best, date_diff_best),
    pattern = run_pattern
  )  %>%
  cols_merge(
    columns = c(minutes_last, pace_last, distance_miles_last, date_last, date_diff_last),
    pattern = run_pattern
  ) %>%
  cols_label(
    duration = "Distance",
    n_runs = 'Total Runs',
    total_miles = "Total Miles",
    minutes_best = md("Best Run<br><span style='font-size:10px'>Time (Miles, Pace)<span>"),
    minutes_last = md("Last Run<br><span style='font-size:10px'>Time (Miles, Pace)<span>"),
    distance_miles_last = "Last Mileage",
    distance_miles_best = "Best Mileage",
  ) %>%
  cols_align(columns = everything(), align='center') %>%
  tab_header(title = "Run Records")

```





# Planning My Next Ride

```{r avg_watts_table}
df_watts <- expand_grid(
    kj = seq(200, 600, by = 1),
    duration = c(10, 15, 20, 30, 45, 60)
  ) %>%
  mutate(avg_watt = calc_watt_average(kj, duration))

df_watts %>%
  ggplot(aes(x = kj, y = avg_watt, color = as.factor(duration))) + 
  geom_line() + 
  labs(title='Avg Watt to Achieve a KJ', 
       y = 'Average Output (Watt)',
       x = 'KJ Total Output') + 
  geom_dl(aes(label = duration), 
          method = list('last.points', hjust = -.2)) + 
  guides(color = 'none')

# Table: Plan your next record
df_watts %>%
  mutate(avg_watt = ceiling(avg_watt)) %>%
  pivot_wider(names_from = duration, values_from = avg_watt) %>%
  DT::datatable(filter = "top", rownames=F)

df_watts %>% 
  filter(kj %% 10 == 0) %>% 
  mutate(avg_watt = ceiling(avg_watt)) %>%
  pivot_wider(
    names_from = duration, 
    values_from = avg_watt) %>%
  gt() %>%
  cols_label(kj = "KJ") %>%
  tab_spanner(columns = 2:7, label = 'Duration (min)') %>%
  cols_align(align='center') %>%
  tab_header('Avg Watts Needed to Achieve a KJ Output')
```
